### ISSUE TITLE
Fix Preprocessor Directive Definition Condition

### ISSUE THREAD

**Issue by windsunsjtu** [ArteryTek/AT32F403A_407_Firmware_Library#4]
In a [AT32F403A_407_Firmware_Library\libraries\cmsis\cm4\device_support\at32f403a_407.h](https://github.com/ArteryTek/AT32F403A_407_Firmware_Library/blob/4dcec715e1510495b6228f145db59cd44d8de1e1/libraries/cmsis/cm4/device_support/at32f403a_407.h#L140), there is a missing `defined` keyword in the condition of a preprocessor directive. The current code is:

```cpp
#if defined (AT32F407RGT7) || defined (AT32F407VGT7) || (AT32F407AVGT7)
```

The correct code should be:

```cpp
#if defined (AT32F407RGT7) || defined (AT32F407VGT7) || defined (AT32F407AVGT7)
```

**Comment by ArteryTek** [comment]
感谢您的问题反馈，下版进行修正，谢谢。
