### ISSUE TITLE
DMA1 and DMA2 request mapping table

### ISSUE THREAD

**Issue by rizacelik** [ArteryTek/AT32F403A_407_Firmware_Library#5]
For [AT32F403A_407_Firmware_Library](https://github.com/ArteryTek/AT32F403A_407_Firmware_Library).

I reviewed all the documentation, but I could not find the DMA1 and DMA2 request mapping table. There is the following table in your documents, but there is no "DMax, Stream, Channel" information. There is only Channel information.
I would be glad if you help me.

![image](https://github.com/ArteryTek/AT32F403A_407_Firmware_Library/assets/19993109/fe070e14-5f8d-4bfd-95c5-004109cd8f8a)

**Comment by ArteryTek** [comment]
Sorry for delay reply.
F403A/407 series support fixed and flexible DMA mode, fixed dma request mapping table as you attached, please refer to section 9.3.8 of reference manul for flexible dma request mapping table.
User can to program any peripherals request sources in specify dma channel with flexible DMA mode.
